language: python
python:
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: alejogaci
  password:
    secure: ssjU68Cp2yJe0ZpeLmHsOKjgwImjx9kMa6YWAu+IXrPQNF3KJdM8/wP2CqPyEoJ6EIla+hXiJVDL8ZBSQb44nP/hCZcMClRZbLqBTBB2FldwTswF8vtbGU4R+we9YSwx+OpJrSHPYc7WZ77Y6pqxcjn5uT2kwDQmHc7dEYjoD3wkuBc8HFym4OYSbIkBx7xGc6usul6wUsMaCMPWBaSWhdtlb10GK2Sb/Yn2dL1Z4AMTtToZ5BKOMZz51sqbntYsgDgfnUAxYM7pzbuD9SENWc8hpq7gC7OtX0WdFsT/YTY1Llj8RYnwxDga60L3t50Bch0XtPEzGyG9sIZwyS2dPJ7lWpiY1+c6KM+j36xsp1sEA8KC8OHB+mbJYQljjfi9CTaCGRYHttvuFod3JpmKGqOcqXWMgzwHxVBlum9gPrKPzwEY5wgwr/D8VZng2a1hGd2Nu8FQfcnvwm6XKe4OVJciMhLRTy5klw0HNZ488PEfe3wQ+E3i5Lr0M9BNeDY+c60mImo59SB0kg7VUFDNUtyGpaSw0WG7XBVbwSa7KecS/obRm4MY2x98L9OmIUD3WNuSga+z86382cnV9QH66/3j48Ii+uLrbqFix26l7W0eer+HTn7zlkLNZRopyPem0JNFGmPlJMIb02pvw04OAO0sQ7LmzbrGkCflrkpl2t0=
  on:
    tags: true
    repo: alejogaci/decodificador
    python: 3.6
